<?php 

function sendNotif($to, $notif){
  $apiKey = "AAAA7AhR99g:APA91bG189OsUI34-X8dzT326MP5ZS3zXVq12FxqkPsQ2KKtBY1zC01xbJm5ceTpOV22nGlKQknk8jDdmXZs2zYOgAZpaeIMiTjLlATaTvp4zfBoP80-u6TK-y6VWwEOWW3WkO8EeYCa";

  // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
  $ch = curl_init();

  $url = "https://fcm.googleapis.com/fcm/send";
  $fields = json_encode(array(
                              'to' => $to, 
                              'notification' => $notif
                              )); 

  curl_setopt($ch, CURLOPT_URL, $url);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($ch, CURLOPT_POST, 1);
  curl_setopt($ch, CURLOPT_POSTFIELDS,($fields));

  $headers = array();
  $headers[] = 'Authorization: key ='.$apiKey;
  $headers[] = 'Content-Type: application/json';
  curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

  $result = curl_exec($ch);
  if (curl_errno($ch)) {
      echo 'Error:' . curl_error($ch);
  }
  curl_close($ch);
}

$to = 'cbJ5KZhrQLOeLtpMawKtgv:APA91bHqiRJg2g2hU3RsbdfqAM4Q5nvsS95HA0ih4accrvJ6eyNEHqZ0r3V7MZs6EBwPJyIepXpMRcSdE57-4tDfTF94QWKnKz3GkgtXKLPBb5y5Almx15DVHgPrYF8gcuRq5FL5QoTy';
$notif = array(
  'title' => 'Notif From PHP Native, Tipe : Single Message',
  'body' => 'Notif From PHP Native, Tipe : Single Message'
);

sendNotif($to, $notif);

?>